name: Tag Creation with Reviewer Approval

on:
  push:
    tags:
      - 'v*' # Match tags starting with 'v'

jobs:
  require_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for approval
        uses: trstringer/manual-approval@v1
        with:
          issue_title: "Tag Creation Request for ${{ github.ref }}"
          body: "Please review and approve the tag creation."
          assignees: ${{ secrets.disk2devops }} # Replace with reviewer username

  create-tag:
    needs: require_approval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        run: |
          git tag ${{ github.ref }}
          git push origin ${{ github.ref }}
